### ISSUE TITLE
First Version of Todo.txt Parser using TDD

### ISSUE THREAD

**Issue by marcus-grant** [marcus-grant/todo.txt#3]
This should follow the [todo.txt rules](https://github.com/todotxt/todo.txt) format as closely as possible.

**File Reading**
* [ ] error on non-UTF-8 formats
* [ ] number of `lines` reflects number of lines in file
* [ ] `\n` breaks a line
* [ ] `\r\n` breaks a line
* [ ] every line inside `lines` should have the same string as the line of the file excluding whitespaces
* [ ] creates a temporary 2d array `tokens` that holds substrings seperated by spaces
* [ ] a non-whitespace, `\s` on regex, match for every `token` exists from its line in `lines`
* [ ] no `token` is out of order from its place in `lines`
* [ ] every non-whitespace character in `lines` has a match in `tokens`
* [ ] no `token` appears in the wrong *row* of its 2d array
* [ ] no non-whitespace substring of the line should be out of order in `tokens
* [ ] no token has a whitespace `\s` regex match
* [ ] once `tokens` is created, `lines` is deleted from memory
* [ ] for every row of `tokens` an empty `Task` is created
* [ ] every `Task` has `nil`in its properties
* [ ] # `Tasks` == `tokens` rows on creation

### If Priority Exists, it's ALWAYS the First Token
* A priority is a token, *ie substring surrounded by whitespace*, of three characters, in order...
  1. Opening parenthesis `(`
  2. An upper-case Letter `A` through `Z`
  3. Closing parenthesis `)`
* [ ] for every `(A-Z)` (single upcase letter), as first `token` `priority` equals the same `A` to `Z` character
  * cycle through every combination of `(A)` through `(Z)` & check `Task`'s priority for only 1 equal letter
* [ ] `priority` == `nil` if `(a)` is in first `token`
* [ ] `priority` == `nil` if `(1)` is first `token`
* [ ] `priority` == `nil` if `A` is first `token`
* [ ] `priority` == `nil` if `x` is first `token`
* [ ] `priority` == `nil` if `2018-01-01` is first `token`
* [ ] `priority` == `nil` if `-(B)` is first token
* [ ] `priority` == `nil` if `(C)-->` is first token
* [ ] `priority` == `nil` if `)D]` is first token
* [ ] if `(A-Z)` is any other `token` than 1st, `priority` == `nil`
* [ ] `priority` is `nil` if no `(A-Z)` exists anywhere as a `token`

### A Task's Creation Date May Optionally Appear After Priority Token
* [ ] a date is of format `####-##-##` (decimal chars) `YYYY-MM-DD`
  * [ ] 1st token == `##-##` `created`=`nil`, `priority`=`nil`
  * [ ] 1st token == `##/##` `created`=`nil`, `priority`=`nil`
  * [ ] 1st token == `foobar` `created`=`nil` `priority`=`nil`
* [ ]  If no priority exists, it appears as 1st token
  * [ ] 1st token == `YYYY-MM-DD`, `created` == `"YYYY-MM-DD"` & `priority` == `nil`
* [ ] If priority exists, creation date appears directly after it
  * [ ] `token[x][0]`= `(A)` `token[x][1]`=`YYYY-MM-DD` `created`=`YYYY-MM-DD`, `priority`=`A`
  * [ ] `token[x][0]`= `(A)` `token[x][1]`=`##/##` `created`=`nil` `priority`=`A`
  * [ ] `token[x]0]`=`(A)` `token[x]1]`=`something` `created`=`nil`, `priority`=`A`
* [ ] Creation date never appears 2nd or later if no priority is given, nor 3rd+ if a priority is given
  * [ ] `(A) Call Mom 2011-03-02`, `created` == `nil`
  * [ ] `Call Mom 2011-03-02`, `created` == `nil`

### A Task's Due Date May Optionally Prepend A Creation Date
* [ ] A creation date is required after a due date if there is a due date
  * [ ] `2011-10-01 2011-09-29 do something` `created`=`2011-09-29` `due`=`2011-10-01`
  * [ ] `(C) 2011-10-01 2011-09-29 do something` `created`=`2011-09-29` `due`=`2011-10-01`
  * [ ] `mop up 2012-12-12 2012-12-11`, `created`=`nil` `due`=`nil`
  * [ ] ` 2012-12-12 mop up 2012-12-11`, `created`=`2012-12-12` `due`=`nil`
  * [ ] `2012-12-12 (A) 2012-12-11` `created`=`2012-12-12` `due`=`nil`
  * [ ] `12/12 12-11 mop up` `created`=`nil` `due`=`nil`

### Contexts & projects can appear in any token *after* priority & date
* [ ] *contexts* are preceded by `@`
  * [ ] `YYYY-MM-DD YYYY-MM-DD clean toilet @home` `context[0]`=`home`
  * [ ] `(A) YYYY-MM-DD YYYY-MM-DD @home clean toilet` `context[0]`=`home`
  * [ ] `YYYY-MM-DD YYYY-MM-DD clean toilet home` `context[0]`=`nil`
  * [ ] `YYYY-MM-DD clean toilet me@gmail.com` `context[0]`=`nil`
* [ ] *contexts* can't appear before a valid date or valid priority
  * [ ] `@home YYYY-MM-DD clean toilet` `context[0]`=`nil`
  * [ ] `@home (A) YYYY-MM-DD clean toilet` `context[0]`=`nil`
  * [ ] `YYYY-MM-DD clean toilet 2+2` `context[0]`=`nil`
* [ ] *projects* are preceeded by `+`
  * [ ] `YYYY-MM-DD YYYY-MM-DD clean toilet +home` `project[0]`=`home`
  * [ ] `(A) YYYY-MM-DD YYYY-MM-DD +home clean toilet` `project[0]`=`home`
  * [ ] `YYYY-MM-DD YYYY-MM-DD clean toilet home` `project[0]`=`nil`
* [ ] *projects* can't appear before a valid date or valid priority
  * [ ] `+home YYYY-MM-DD clean toilet` `project[0]`=`nil`
  * [ ] `+home (A) YYYY-MM-DD clean toilet` `project[0]`=`nil`
* *projects* & *contexts* are tokens so if the token tests pass you know there's no whitespace
* [ ] tasks may have 0 to many *projects* & *contexts*, but any that appear before dates or priority get ignored
  * [ ] `YYYY-MM-DD YYYY-MM-DD clean toilet @home @clean +home +clean` `context`=`["home", "clean"]`, `project`=`["home", "clean"]`
  * [ ] `@clean +clean (A) YYYY-MM-DD @home +clean clean toilet `context`=`["home"]` `project`=`["home"]` 
  * [ ] `something @todo +done` `context[0]`=`nil`

**Completion Tag**
* [ ] if first token is `x`, a single **lower case** x, `Task` has `completed` as `true`
* [ ] if first token is anything but `x` (low case) `complete` is `false` after reading row of `tokens`
* [ ] if first `token` is `x` & second is `(A-Z)` mark as invalid and `complete` is `true`

**

* [ ] if `pri:A-Z` exists in row, `A-Z` is recorded in `priority` of `Task`
* [ ] if `pri:A-Z` exists in row, but first token isn't `x` (lowercase x), mark as invalid & `priority` is `nil`
* [ ] if `pri` exists as well as `(A-Z)` in first token, ignore the `key:value` version
* [ ] if same as above, the `pri:A-Z` tag is reflected in `Task` `priority` as that value
* [ ] if the first token is `(LETTER)` **nothing** should follow it inside the token
* [ ] mark as invalid if any token precedes `(LETTER)`
* [ ] Recognizes any `####-##-##` token as a date (`#`) is a decimal digit
* [ ] Record `YYYY-MM-DD` as a date
* [ ] If a single date token exists, it should be recorded as a `creation` property
* [ ] If no `####-##-##` token is detected, a `Task` should be recorded as 
* [ ] If two dates exist, the first should be recorded as a `due` property
* [ ] a single date that doesn't immediately follow a priority token is invalid
* [ ] if no priority exists, a single date that isn't the first token is invalid
* [ ] if two dates exist, one always follows the other token
* [ ] if a thid date token is detected, the entry is invalid
* [ ] If two dates exist, the entry should be marked invalid if the creation > due
* [ ] if a task is complete no `(LETTER)` tag should exist
* [ ] if a task is complete the priority should appear in the keyvalue tags as `!!:LETTER`
* [ ] if a task is complete it should still be valid if it isn't recorded at all anymore
* [ ] The only thing following `!!:` should be a **single upper-case** letter

* [ ] validates that no single `x` token exists anywhere but in the first token
* [ ] recognizes that a single `x` in the description tag isn't a completion tag

* [ ] a `created:####-##-##` keyvalue tag is recorded as `created` date in `Task`

**TODO**
* [ ] These should be added into a planning issue
invalidate several date formats
detects local total & available RAM correctly
should never use more than 32MiB of RAM, period.
should never use more than 16MiB of RAM on systems with <1GB RAM total or <16MB RAM avail.
should never use more than 8MiB of RAM on systems with <512MB RAM total or <8MB RAM avail.
should never use more than 4MiB of RAM on systems with <256MB RAM or  <4MB of RAM
should reject non visible characters
should allow any visible non-latin characters in UTF-8
